<script setup lang="ts">
import { computed } from "vue";
import { RouterLink } from "vue-router";
import {
  CloudIcon,
  ShieldCheckIcon,
  RocketLaunchIcon,
  ArrowRightIcon,
} from "@heroicons/vue/24/outline";
import { useI18n } from "@/i18n";

const { t } = useI18n();

// Screenshots of the real apps, regenerated by scripts/onboarding-tour/capture.sh.
// Phone shots sit beside their caption; the wide kitchen and dashboard shots
// need the card's full width to stay legible.
const tourSteps = computed(() =>
  (
    [
      {
        key: "order",
        src: "/tour/1-order.jpg",
        width: 780,
        height: 1328,
        wide: false,
      },
      {
        key: "kitchen",
        src: "/tour/2-kitchen.jpg",
        width: 2360,
        height: 1640,
        wide: true,
      },
      {
        key: "tracking",
        src: "/tour/3-tracking.jpg",
        width: 780,
        height: 1328,
        wide: false,
      },
      {
        key: "dashboard",
        src: "/tour/4-dashboard.jpg",
        width: 2880,
        height: 1800,
        wide: true,
      },
    ] as const
  ).map((step) => ({
    ...step,
    title: t(`home.tour.steps.${step.key}.title`),
    description: t(`home.tour.steps.${step.key}.description`),
    alt: t(`home.tour.steps.${step.key}.alt`),
  })),
);

// The live showcase shop (restaurants.is_demo). Unset until the platform has
// created one, and then the button stays hidden rather than 404ing.
const demoShopUrl = (() => {
  const id = import.meta.env.VITE_DEMO_RESTAURANT_ID;
  const base = import.meta.env.VITE_CUSTOMER_APP_URL;
  return id && base
    ? `${base.replace(/\/+$/, "")}/restaurant/${id}/shop/order-type`
    : null;
})();

const features = computed(() => [
  {
    icon: CloudIcon,
    title: t("home.features.hosted.title"),
    description: t("home.features.hosted.description"),
  },
  {
    icon: ShieldCheckIcon,
    title: t("home.features.secure.title"),
    description: t("home.features.secure.description"),
  },
  {
    icon: RocketLaunchIcon,
    title: t("home.features.assisted.title"),
    description: t("home.features.assisted.description"),
  },
]);
</script>

<template>
  <div>
    <!-- Hero Section -->
    <section class="pt-16 pb-20 text-center sm:pt-20 sm:pb-24">
      <h1
        class="text-4xl font-semibold tracking-tight text-ios-text sm:text-5xl"
      >
        {{ t("home.hero.titleLine1") }}<br />
        <span class="text-primary-500">{{ t("home.hero.titleLine2") }}</span>
      </h1>
      <p
        class="mx-auto mt-5 max-w-xl text-base leading-relaxed text-gray-500 sm:text-lg"
      >
        {{ t("home.hero.subtitle") }}
      </p>

      <div class="mt-10 flex flex-col items-center gap-4">
        <RouterLink
          to="/apply"
          class="inline-flex items-center justify-center rounded-full bg-primary-500 px-8 py-3.5 text-base font-semibold text-white shadow-sm transition-all duration-300 ease-out hover:-translate-y-0.5 hover:bg-primary-600 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2"
        >
          {{ t("home.hero.ctaApply") }}
          <ArrowRightIcon class="ml-2 h-4 w-4" />
        </RouterLink>
        <a
          href="#how-it-works"
          class="text-sm font-medium text-primary-700 transition-colors duration-200 hover:text-primary-800"
        >
          {{ t("home.hero.ctaTour") }}
        </a>
      </div>
    </section>

    <!-- Features -->
    <section class="grid grid-cols-1 gap-5 md:grid-cols-3 md:gap-6">
      <div
        v-for="feature in features"
        :key="feature.title"
        class="group flex flex-col rounded-3xl bg-white p-8 shadow-card transition-all duration-300 ease-out hover:-translate-y-1 hover:shadow-[0_12px_32px_rgba(0,0,0,0.08)]"
      >
        <div
          class="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary-50"
        >
          <component
            :is="feature.icon"
            class="h-6 w-6 text-primary-500"
            aria-hidden="true"
          />
        </div>
        <h3 class="mt-5 text-lg font-semibold text-ios-text">
          {{ feature.title }}
        </h3>
        <p class="mt-2 text-sm leading-relaxed text-gray-500">
          {{ feature.description }}
        </p>
      </div>
    </section>

    <!-- How it works: real screens from the customer, kitchen and admin apps -->
    <section id="how-it-works" class="mt-20 scroll-mt-24">
      <div class="text-center">
        <h2
          class="text-2xl font-semibold tracking-tight text-ios-text sm:text-3xl"
        >
          {{ t("home.tour.title") }}
        </h2>
        <p
          class="mx-auto mt-3 max-w-xl text-sm leading-relaxed text-gray-500 sm:text-base"
        >
          {{ t("home.tour.subtitle") }}
        </p>
      </div>

      <ol class="mt-10 space-y-6">
        <li
          v-for="(step, index) in tourSteps"
          :key="step.key"
          :data-tour-step="step.key"
          class="overflow-hidden rounded-3xl bg-white p-6 shadow-card sm:p-8"
          :class="
            step.wide
              ? ''
              : 'grid items-center gap-6 sm:grid-cols-[1fr_auto] sm:gap-10'
          "
        >
          <div>
            <span
              class="inline-flex h-8 w-8 items-center justify-center rounded-full bg-primary-50 text-sm font-semibold text-primary-700"
              aria-hidden="true"
            >
              {{ index + 1 }}
            </span>
            <h3 class="mt-4 text-lg font-semibold text-ios-text sm:text-xl">
              {{ step.title }}
            </h3>
            <p
              class="mt-2 max-w-md text-sm leading-relaxed text-gray-500 sm:text-base"
            >
              {{ step.description }}
            </p>
          </div>
          <img
            :src="step.src"
            :alt="step.alt"
            :width="step.width"
            :height="step.height"
            loading="lazy"
            decoding="async"
            class="h-auto bg-ios-bg shadow-card"
            :class="
              step.wide
                ? 'mt-6 w-full rounded-2xl'
                : 'mx-auto w-full max-w-[240px] rounded-[1.75rem]'
            "
          />
        </li>
      </ol>

      <div v-if="demoShopUrl" class="mt-8 text-center">
        <a
          :href="demoShopUrl"
          target="_blank"
          rel="noopener"
          data-testid="try-demo-shop"
          class="inline-flex items-center justify-center rounded-full bg-white px-6 py-3 text-sm font-semibold text-primary-700 shadow-card transition-all duration-300 ease-out hover:-translate-y-0.5 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2"
        >
          {{ t("home.tour.tryDemo") }}
        </a>
        <p class="mt-2 text-xs text-gray-500">
          {{ t("home.tour.tryDemoHint") }}
        </p>
      </div>
    </section>

    <!-- Subtle CTA -->
    <section
      class="mt-16 flex flex-col items-center justify-between gap-5 rounded-3xl bg-white p-8 shadow-card sm:flex-row sm:gap-6 sm:p-10"
    >
      <div class="text-center sm:text-left">
        <h2 class="text-lg font-semibold text-ios-text sm:text-xl">
          {{ t("home.cta.title") }}
        </h2>
        <p class="mt-1 text-sm text-gray-500">
          {{ t("home.cta.subtitle") }}
        </p>
      </div>
      <RouterLink
        to="/apply"
        class="inline-flex shrink-0 items-center justify-center rounded-full bg-primary-500 px-6 py-3 text-sm font-semibold text-white shadow-sm transition-all duration-300 ease-out hover:-translate-y-0.5 hover:bg-primary-600 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2"
      >
        {{ t("home.cta.button") }}
        <ArrowRightIcon class="ml-2 h-4 w-4" />
      </RouterLink>
    </section>
  </div>
</template>
